fixed for JVNVU#92669710

diff --git a/src/install b/src/install
--- a/src/install
+++ b/src/install
@@ -329,13 +329,6 @@ case $UNAME in
 # #					${INSTALL} ${INSTALLDLLFLAGS} ${DISTDIR}/DLL/OpenSSL/${ARCH}/libeay32.dll ${DISTDIR}/bin
 # #					${INSTALL} ${INSTALLDLLFLAGS} ${DISTDIR}/DLL/OpenSSL/${ARCH}/libssl32.dll ${DISTDIR}/bin
 # #					${INSTALL} ${INSTALLDLLFLAGS} ${DISTDIR}/DLL/OpenSSL/${ARCH}/ssleay32.dll ${DISTDIR}/bin
-# 					# for JVNVU#92669710
-# 					if [ -x "${QTROOT}/bin/Qt5Core_patched.dll" ] ; then
-# 						${INSTALL} ${INSTALLDLLFLAGS} ${QTROOT}/bin/Qt5Core_patched.dll ${DISTDIR}/bin/Qt5Core.dll
-# 					else
-# 						echo "NOT Found Qt5Core_patched.dll file!!"
-# 						exit 1;
-# 					fi
 # 					;;
 # 				*)
 # 					echo "$0 : Not support platform."
@@ -343,6 +336,15 @@ case $UNAME in
 # 					;;
 # 			esac
 # 			fi
+			if [ "$TARGET" = "msvc-xp" ] ; then
+					# for JVNVU#92669710
+					if [ -x "${QTROOT}/bin/Qt5Core_patched.dll" ] ; then
+						${INSTALL} ${INSTALLDLLFLAGS} ${QTROOT}/bin/Qt5Core_patched.dll ${DISTDIR}/bin/Qt5Core.dll
+					else
+						echo "NOT Found Qt5Core_patched.dll file!!"
+						exit 1;
+					fi
+			fi
 			# copy executable file
 			echo "copy executable file..."
 			${INSTALL} ${INSTALLEXEFLAGS} "release/${APP}.exe" ${DISTDIR}/bin
