updated install script

diff --git a/src/install b/src/install
--- a/src/install
+++ b/src/install
@@ -233,6 +233,10 @@ case $UNAME in
 				echo "NOT Found ${APP}.exe"
 				exit 1;
 			fi
+			if [ ! -x keylayout/${KLFC}.exe ] ; then
+				echo "NOT Found ${KLFC}.exe"
+				exit 1;
+			fi
 			VERSION=`release/${APP}.exe -vv`
 			# make package string
 			PKGSTRING="${APP}-windows-v${VERSION}-${DATE}.exe"
@@ -265,11 +269,8 @@ case $UNAME in
 			mkdir -p ${DISTDIR}/bin/keylayout
 			${INSTALL} ${INSTALLFLAGS} keylayout/*.kl ${DISTDIR}/bin/keylayout
 			# install key layout file compiler
-			echo "make klfcompiler..."
-			cd keylayout; make clean; make DEFINES=-DPLATFORM_WINDOWS
 			echo "install klfcompiler..."
-			${INSTALL} ${INSTALLEXEFLAGS} ${KLFC}.exe ../${DISTDIR}/bin
-			cd ..
+			${INSTALL} ${INSTALLEXEFLAGS} keylayout/${KLFC}.exe ${DISTDIR}/bin
 			# for TEST
 			${INSTALL} ${INSTALLFLAGS} keylayout/test/*.klx ${DISTDIR}/bin/keylayout
 			# copy manual file
@@ -296,6 +297,10 @@ case $UNAME in
 				echo "NOT Found ${APP}"
 				exit 1;
 			fi
+			if [ ! -x keylayout/${KLFC} ] ; then
+				echo "NOT Found ${KLFC}"
+				exit 1;
+			fi
 			VERSION=`${APP} -vv`
 			# for cygwin
 			# create directory
@@ -308,11 +313,8 @@ case $UNAME in
 			mkdir -p ${DISTDIR}/bin/keylayout
 			${INSTALL} ${INSTALLFLAGS} keylayout/*.kl ${DISTDIR}/bin/keylayout
 			# install key layout file compiler
-			echo "make klfcompiler..."
-			cd keylayout; make clean; make DEFINES=-DPLATFORM_WINDOWS
 			echo "install klfcompiler..."
-			${INSTALL} ${INSTALLEXEFLAGS} ${KLFC}.exe ../${DISTDIR}/bin
-			cd ..
+			${INSTALL} ${INSTALLEXEFLAGS} keylayout/${KLFC}.exe ${DISTDIR}/bin
 			# copy document file
 			${INSTALL} ${INSTALLFLAGS} ../dist/doc/ReadMe.txt ${DISTDIR}/doc
 			${INSTALL} ${INSTALLFLAGS} ../dist/doc/LICENSE.txt ${DISTDIR}/doc
@@ -336,6 +338,10 @@ case $UNAME in
 			echo "NOT Found ${APP}"
 			exit 1;
 		fi
+		if [ ! -x keylayout/${KLFC} ] ; then
+			echo "NOT Found ${KLFC}"
+			exit 1;
+		fi
 		VERSION=`${APP} -vv`
 		# for linux
 		# create directory
@@ -349,10 +355,8 @@ case $UNAME in
 		${INSTALL} ${INSTALLFLAGS} keylayout/*.kl ${DISTDIR}/bin/keylayout
 		# install key layout file compiler
 		echo "make klfcompiler..."
-		cd keylayout; make clean; make DEFINES=-DPLATFORM_LINUX
 		echo "install klfcompiler..."
-		${INSTALL} ${INSTALLEXEFLAGS} ${KLFC} ../${DISTDIR}/bin
-		cd ..
+		${INSTALL} ${INSTALLEXEFLAGS} keylayout/${KLFC} ${DISTDIR}/bin
 		# copy document file
 		${INSTALL} ${INSTALLFLAGS} ../dist/doc/ReadMe.txt ${DISTDIR}/doc
 		${INSTALL} ${INSTALLFLAGS} ../dist/doc/LICENSE.txt ${DISTDIR}/doc
@@ -376,6 +380,10 @@ case $UNAME in
 			echo "NOT Found ${APP}"
 			exit 1;
 		fi
+		if [ ! -x keylayout/${KLFC} ] ; then
+			echo "NOT Found ${KLFC}"
+			exit 1;
+		fi
 		VERSION=`${APP} -vv`
 		# for freebsd
 		# create directory
@@ -389,10 +397,8 @@ case $UNAME in
 		${INSTALL} ${INSTALLFLAGS} keylayout/*.kl ${DISTDIR}/bin/keylayout
 		# install key layout file compiler
 		echo "make klfcompiler..."
-		cd keylayout; make clean; make DEFINES=-DPLATFORM_LINUX
 		echo "install klfcompiler..."
-		${INSTALL} ${INSTALLEXEFLAGS} ${KLFC} ../${DISTDIR}/bin
-		cd ..
+		${INSTALL} ${INSTALLEXEFLAGS} keylayout/${KLFC} ${DISTDIR}/bin
 		# copy document file
 		${INSTALL} ${INSTALLFLAGS} ../dist/doc/ReadMe.txt ${DISTDIR}/doc
 		${INSTALL} ${INSTALLFLAGS} ../dist/doc/LICENSE.txt ${DISTDIR}/doc
@@ -415,17 +421,18 @@ case $UNAME in
 			echo "NOT Found ${APP}.app"
 			exit 1;
 		fi
+		if [ ! -x keylayout/${KLFC} ] ; then
+			echo "NOT Found ${KLFC}"
+			exit 1;
+		fi
 		# strip
 		strip ${APP}.app/Contents/MacOS/${APP}
 		# copy key layout file
 		mkdir -p ${APP}.app/Contents/MacOS/keylayout
 		${INSTALL} ${INSTALLFLAGS} keylayout/*.kl keylayout
 		# install key layout file compiler
-		echo "make klfcompiler..."
-		cd keylayout; make clean; make DEFINES=-DPLATFORM_MACOS
 		echo "install klfcompiler..."
-		${INSTALL} ${INSTALLEXEFLAGS} ${KLFC} ../${APP}.app/Contents/MacOS/
-		cd ..
+		${INSTALL} ${INSTALLEXEFLAGS} keylayout/${KLFC} ${APP}.app/Contents/MacOS/
 		VERSION=`${APP}.app/Contents/MacOS/${APP} -vv`
 		# make package string
 		#PKGSTRING="${APP}-${PKGNAME}-v${VERSION}-${DATE}"
